package:
  format-version: "1.0.0"
  name: "core_apps_sam_d21_da1"
  version: "v3.3.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.11.0"
    - name: "usb"
      type: "package"
      version: "v3.9.0"
